# -*- coding: utf-8 -*-
"""Perceptrons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pWXM_BBK2YlZsXbS7613n3-PjU1CPdw
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('placement.csv')

print(df.shape)
df.head()

sns.scatterplot(x=df['cgpa'],y=df['resume_score'],hue = df['placed'])

x = df.iloc[:,0:2]
y = df.iloc[:,-1]

from sklean.linear_model import Perceptron

